---
# tasks file for minecraft

- name: create minecraft user
  ansible.builtin.user:
    name: minecraft
    comment: Minecraft User
    shell: /bin/bash
    home: "{{ minecraft_home }}"

- ansible.builtin.include_tasks: packages-RedHat.yml

# EOF
