---
# tasks file for minecraft

- name: create minecraft user
  ansible.builtin.user:
    name: minecraft
    comment: Minecraft User
    shell: /bin/bash
    home: "{{ minecraft_home }}"

- ansible.builtin.include_tasks: packages-RedHat.yml

- name: create server directory
  ansible.builtin.file:
    path: "{{ minecraft_home }}/{{ server_name }}"
    state: directory
    owner: minecraft
    group: minecraft
    mode: '0755'

- ansible.builtin.include_tasks: install_jar.yml

# EOF
